spring:
  application:
    name: email-producer

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  email_topic: EMAIL_TOPIC2

server:
  port: 9881